let leads=[
 {id:'LD-2026-0047',name:'Ahmad Firdaus',phone:'+60 12-884 2190',region:'East Malaysia',model:'Yamaha Y16ZR',status:'Assigned',sa:'K2162',time:'8 min ago'},
 {id:'LD-2026-0046',name:'Siti Nur Aina',phone:'+60 17-342 6681',region:'West Malaysia',model:'Honda RS-X',status:'New',sa:'Unassigned',time:'21 min ago'},
 {id:'LD-2026-0045',name:'Jason Lim',phone:'+60 16-778 9033',region:'West Malaysia',model:'Yamaha NVX',status:'Manual review',sa:'K2179',time:'1 hr ago'},
 {id:'LD-2026-0044',name:'Nur Syafiqah',phone:'+60 11-209 4418',region:'East Malaysia',model:'Honda ADV160',status:'Assigned',sa:'K2162',time:'2 hrs ago'},
 {id:'LD-2026-0043',name:'Mohd Rizal',phone:'+60 13-556 8201',region:'East Malaysia',model:'Yamaha LC135',status:'Assigned',sa:'K2162',time:'3 hrs ago'}
];
const statuses={Assigned:'green',New:'', 'Manual review':'red'};
let crmSummary={leads:47,applications:26,conversion:.553,needsAttention:6,completed:2,unreadInbox:4};
let isLive=false;
let currentUser={name:'Nick Jee',role:'ADMIN',region:'ALL'};
const liveRecords={applications:[],inbox:[],outbox:[],catalog:[],pricing:[],team:[]};
const app=document.getElementById('appView');
const loginGate=document.getElementById('loginGate');
const appShell=document.getElementById('appShell');
const loginForm=document.getElementById('loginForm');
const nav=[...document.querySelectorAll('.nav-item')];
const pageNames={leads:'Leads',applications:'Applications',inbox:'Customer Inbox',outbox:'Message Outbox',catalog:'Motor Catalog',pricing:'Loan Pricing',team:'Branches & Team',settings:'Settings'};
function head(title,desc,eyebrow='JomKaki Motor CRM'){const now=new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kuala_Lumpur'}).format(new Date());return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p></div><div class="page-actions"><div class="date-chip">${now}</div><button class="secondary" data-export>Export</button></div></div>`}
function dashboard(){
 const firstName=String(currentUser.name||'User').split(' ')[0];
 app.innerHTML=head(`Good afternoon, ${escapeHtml(firstName)}.`,`Here is what is happening across ${currentUser.role==='ADMIN'?'your sales operation':pretty(currentUser.region)} today.`)+`
 <div class="kpi-grid">
  <article class="kpi"><div class="label">Total leads</div><strong>${crmSummary.leads}</strong><span class="trend">${isLive?'â— Live from CRM':'Preview data'}</span></article>
  <article class="kpi"><div class="label">Active applications</div><strong>${crmSummary.applications}</strong><span class="trend">${isLive?'â— Live from CRM':'Preview data'}</span></article>
  <article class="kpi"><div class="label">Lead conversion</div><strong>${(crmSummary.conversion*100).toFixed(1)}%</strong><span class="trend">Applications Ã· leads</span></article>
  <article class="kpi"><div class="label">Needs attention</div><strong>${crmSummary.needsAttention}</strong><span class="trend alert">Manual review and recovery</span></article>
 </div>
 <div class="section-grid">
  <article class="card"><div class="card-head"><h2>Lead activity</h2><span>Last 7 days</span></div><div class="chart">${[42,61,47,72,54,83,68].map((x,i)=>`<div class="bar-wrap"><div class="bar" style="height:${x}%"></div><span>${['Wed','Thu','Fri','Sat','Sun','Mon','Tue'][i]}</span></div>`).join('')}</div><div class="funnel"><div class="funnel-row"><span>New leads</span><div class="track"><i style="width:100%"></i></div><strong>${crmSummary.leads}</strong></div><div class="funnel-row"><span>Applications</span><div class="track"><i style="width:${Math.min(crmSummary.conversion*100,100)}%"></i></div><strong>${crmSummary.applications}</strong></div><div class="funnel-row"><span>Completed</span><div class="track"><i style="width:${crmSummary.applications?Math.min(crmSummary.completed/crmSummary.applications*100,100):0}%"></i></div><strong>${crmSummary.completed}</strong></div></div></article>
  <div><article class="card"><div class="card-head"><h2>Action centre</h2><button>View all</button></div><div class="list">
   <div class="list-row"><div class="list-icon">!</div><div><strong>Cases needing attention</strong><span>Manual review, recovery or failed delivery</span></div><span class="pill">${crmSummary.needsAttention} ${crmSummary.needsAttention===1?'case':'cases'}</span></div>
   <div class="list-row"><div class="list-icon">â†»</div><div><strong>Unread customer messages</strong><span>Inbox records awaiting processing</span></div><span class="pill">${crmSummary.unreadInbox}</span></div>
   <div class="list-row"><div class="list-icon">âœ“</div><div><strong>Message delivery</strong><span>Outbox is operating normally</span></div><span class="pill green">Healthy</span></div>
  </div></article><article class="card" style="margin-top:16px"><div class="card-head"><h2>Latest leads</h2><button data-jump="leads">Open leads</button></div><div class="list">${leads.slice(0,3).map(l=>`<div class="list-row"><div class="avatar">${initials(l.name)}</div><div><strong>${l.name}</strong><span>${l.model} Â· ${l.time}</span></div><span class="pill ${statuses[l.status]||''}">${l.status}</span></div>`).join('')}</div></article></div>
 </div>`;
 document.querySelector('[data-jump="leads"]')?.addEventListener('click',()=>setView('leads'));
}
function initials(n){return n.split(' ').slice(0,2).map(x=>x[0]).join('')}
function leadsView(){app.innerHTML=head('Leads','Manage enquiries, ownership and customer follow-up.','Sales pipeline')+`<article class="card table-card"><div class="toolbar"><input id="leadSearch" placeholder="Search leadsâ€¦"><select id="statusFilter"><option value="">All statuses</option><option value="NEW">New</option><option value="ASSIGNED">Assigned</option><option value="QUALIFYING">Qualifying</option><option value="FOLLOW_UP">Follow up</option><option value="MANUAL_REVIEW">Manual review</option><option value="CLOSED">Closed</option></select><select id="regionFilter"><option value="">All regions</option><option value="SARAWAK">East Malaysia</option><option value="WEST_MALAYSIA">West Malaysia</option></select><button class="primary" data-add-lead>ï¼‹ Add lead</button></div><table class="data-table"><thead><tr><th>Customer</th><th>Lead ID</th><th>Phone</th><th>Region</th><th>Motor interest</th><th>Status</th><th>Assigned SA</th><th>Last activity</th><th></th></tr></thead><tbody id="leadRows"></tbody></table></article>`;renderLeadRows(leads);document.getElementById('leadSearch').oninput=filterLeads;document.getElementById('statusFilter').onchange=filterLeads;document.getElementById('regionFilter').onchange=filterLeads}
function renderLeadRows(rows){document.getElementById('leadRows').innerHTML=rows.map(l=>`<tr><td><div class="customer"><div class="mini">${initials(l.name)}</div><div><strong>${escapeHtml(l.name)}</strong><small>${escapeHtml(l.id)}</small></div></div></td><td>${escapeHtml(l.id)}</td><td>${escapeHtml(l.phone)}</td><td>${pretty(l.region)}</td><td>${escapeHtml(l.model)}</td><td><span class="pill ${String(l.status).includes('REVIEW')?'red':'green'}">${pretty(l.status)}</span></td><td>${escapeHtml(l.sa)}</td><td>${escapeHtml(l.time)}</td><td><button class="row-action" data-edit-lead="${escapeHtml(l.id)}">Open</button></td></tr>`).join('')||'<tr><td colspan="9">No matching leads found.</td></tr>'}
function filterLeads(){const q=document.getElementById('leadSearch').value.toLowerCase(),s=document.getElementById('statusFilter').value,r=document.getElementById('regionFilter').value;renderLeadRows(leads.filter(l=>(!q||Object.values(l).join(' ').toLowerCase().includes(q))&&(!s||l.status===s)&&(!r||l.region===r)))}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function pretty(value){return String(value||'â€”').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())}
function closeModal(){document.querySelector('.modal-backdrop')?.remove()}
function showModal(title,body){closeModal();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><section class="modal"><header><div><div class="eyebrow">JomKaki Motor CRM</div><h2>${title}</h2></div><button class="modal-close" aria-label="Close">Ã—</button></header><div class="modal-content">${body}</div></section></div>`);document.querySelector('.modal-close').onclick=closeModal;document.querySelector('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}
async function apiAction(data){const response=await fetch('/api/crm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to save changes.');return payload}
async function ensureTeam(){if(!liveRecords.team.length){const response=await fetch('/api/crm?resource=team');const payload=await response.json();if(payload.live)liveRecords.team=payload.records||[]}}
function saOptions(selected=''){return `<option value="">Unassigned</option>${liveRecords.team.map(sa=>`<option value="${escapeHtml(sa.id)}" ${sa.id===selected?'selected':''}>${escapeHtml(sa.id)} Â· ${escapeHtml(sa.name)} Â· ${escapeHtml(sa.branch)}</option>`).join('')}`}
function setSaving(form,saving,label='Save changes'){const button=form.querySelector('button[type="submit"]');if(!button)return;button.disabled=saving;button.textContent=saving?'Savingâ€¦':label}
async function refreshCurrent(view){await loadLiveCrm();if(view==='leads')leadsView();else await loadRecordsView(view)}
async function openLeadEditor(lead){await ensureTeam();showModal(`Lead Â· ${escapeHtml(lead.id)}`,`<div class="detail-grid"><div class="detail-card"><span>Customer</span><strong>${escapeHtml(lead.name)}</strong><small>${escapeHtml(lead.phone)}</small></div><div class="detail-card"><span>Interest</span><strong>${escapeHtml(lead.model)}</strong><small>${pretty(lead.region)}</small></div></div><form id="leadEditForm" class="form-grid"><label>Status<select name="status"><option value="NEW">New</option><option value="ASSIGNED">Assigned</option><option value="QUALIFYING">Qualifying</option><option value="FOLLOW_UP">Follow up</option><option value="MANUAL_REVIEW">Manual review</option><option value="CLOSED">Closed</option></select></label><label>Assigned SA<select name="sa">${saOptions(lead.sa==='Unassigned'?'':lead.sa)}</select></label><label>Branch ID<input name="branch" value="${escapeHtml(lead.branch||'')}"></label><label>Next follow-up<input name="nextFollowUp" type="datetime-local" value="${escapeHtml(String(lead.nextFollowUp||'').slice(0,16))}"></label><label class="full">Internal notes<textarea name="notes" rows="4">${escapeHtml(lead.notes||'')}</textarea></label><div class="form-actions full"><button type="button" class="secondary" data-whatsapp>Queue WhatsApp</button><button class="primary" type="submit">Save changes</button></div></form>`);const form=document.getElementById('leadEditForm');form.status.value=lead.status||'NEW';form.onsubmit=async e=>{e.preventDefault();setSaving(form,true);try{await apiAction({action:'updateLead',id:lead.id,...Object.fromEntries(new FormData(form))});toast('Lead updated successfully.');closeModal();await refreshCurrent('leads')}catch(error){toast(error.message)}finally{setSaving(form,false)}};form.querySelector('[data-whatsapp]').onclick=()=>openMessageComposer(lead)}
async function openNewLead(){await ensureTeam();showModal('Create new lead',`<form id="newLeadForm" class="form-grid"><label>Customer name<input name="name" required></label><label>Phone number<input name="phone" placeholder="6012â€¦" required></label><label>Region<select name="region"><option value="SARAWAK">East Malaysia</option><option value="WEST_MALAYSIA">West Malaysia</option></select></label><label>Preferred language<select name="language"><option value="BM">Bahasa Malaysia</option><option value="EN">English</option><option value="ZH">ä¸­æ–‡</option></select></label><label>Motor / enquiry<input name="enquiry" placeholder="Yamaha Y16ZR"></label><label>Assigned SA<select name="sa">${saOptions()}</select></label><label>State<input name="state"></label><label>City or area<input name="city"></label><label class="full">Notes<textarea name="notes" rows="3"></textarea></label><label class="check full"><input name="optIn" type="checkbox" checked> Customer consents to WhatsApp follow-up</label><div class="form-actions full"><button class="primary" type="submit">Create lead</button></div></form>`);const form=document.getElementById('newLeadForm');form.onsubmit=async e=>{e.preventDefault();setSaving(form,true,'Create lead');try{const data=Object.fromEntries(new FormData(form));data.optIn=form.optIn.checked;await apiAction({action:'createLead',...data});toast('New lead created.');closeModal();await refreshCurrent('leads')}catch(error){toast(error.message)}finally{setSaving(form,false,'Create lead')}}}
function openMessageComposer(record){showModal('Queue WhatsApp message',`<form id="messageForm" class="form-grid"><label>Phone<input name="phone" value="${escapeHtml(record.phone||'')}" required></label><label>Language<select name="language"><option value="MS">Bahasa Malaysia</option><option value="EN">English</option><option value="ZH">ä¸­æ–‡</option></select></label><label class="full">Message<textarea name="message" rows="7" required></textarea></label><p class="notice full">WhatsApp Cloud is not connected yet. This message will remain PENDING in Message Outbox and will not be sent automatically.</p><div class="form-actions full"><button class="primary" type="submit">Add to outbox</button></div></form>`);const form=document.getElementById('messageForm');form.onsubmit=async e=>{e.preventDefault();setSaving(form,true,'Add to outbox');try{await apiAction({action:'queueMessage',leadId:record.id||'',applicationId:record.applicationId||'',...Object.fromEntries(new FormData(form))});toast('Message added to outbox.');closeModal()}catch(error){toast(error.message)}finally{setSaving(form,false,'Add to outbox')}}}
async function openApplicationEditor(record){await ensureTeam();showModal(`Application Â· ${escapeHtml(record.id)}`,`<div class="detail-grid"><div class="detail-card"><span>Customer</span><strong>${escapeHtml(record.customer)}</strong><small>${escapeHtml(record.phone||'')}</small></div><div class="detail-card"><span>Product</span><strong>${escapeHtml(record.product||'Not selected')}</strong><small>${pretty(record.region)}</small></div></div><form id="applicationEditForm" class="form-grid"><label>Current stage<select name="stage"><option value="APPLICATION_DETAILS_PENDING">Application details pending</option><option value="DOCUMENT_COLLECTION">Document collection</option><option value="DOCUMENT_VERIFICATION">Document verification</option><option value="CREDIT_ASSESSMENT">Credit assessment</option><option value="BRANCH_HANDOVER">Branch handover</option><option value="RECOVERY_PENDING">Recovery pending</option><option value="COMPLETED">Completed</option></select></label><label>Status<select name="status"><option value="IN_PROGRESS">In progress</option><option value="MANUAL_REVIEW">Manual review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select></label><label>Assigned SA<select name="sa">${saOptions(record.sa==='Unassigned'?'':record.sa)}</select></label><label>Branch ID<input name="branch" value="${escapeHtml(record.branch||'')}"></label><label>Next follow-up<input name="nextFollowUp" type="datetime-local" value="${escapeHtml(String(record.nextFollowUp||'').slice(0,16))}"></label><label>SA review required<select name="reviewRequired"><option value="FALSE">No</option><option value="TRUE">Yes</option></select></label><label class="full">Handover / review reason<textarea name="handoverReason" rows="4"></textarea></label><div class="form-actions full"><button type="button" class="secondary" data-app-whatsapp>Queue WhatsApp</button><button class="primary" type="submit">Save changes</button></div></form>`);const form=document.getElementById('applicationEditForm');form.stage.value=record.stage||'APPLICATION_DETAILS_PENDING';form.status.value=record.status||'IN_PROGRESS';form.reviewRequired.value=String(record.reviewRequired).toUpperCase()==='TRUE'?'TRUE':'FALSE';form.onsubmit=async e=>{e.preventDefault();setSaving(form,true);try{await apiAction({action:'updateApplication',id:record.id,...Object.fromEntries(new FormData(form))});toast('Application updated successfully.');closeModal();await refreshCurrent('applications')}catch(error){toast(error.message)}finally{setSaving(form,false)}};form.querySelector('[data-app-whatsapp]').onclick=()=>openMessageComposer({phone:record.phone,applicationId:record.id})}
function recordsView(view){
 const configs={
  applications:{desc:'Track every financing case from intake to completion.',cols:[['customer','Customer'],['id','Application ID'],['region','Region'],['stage','Current stage'],['status','Status'],['sa','Assigned SA'],['updated','Updated']]},
  inbox:{desc:'Review incoming customer messages and processing status.',cols:[['customer','Customer / phone'],['id','Message ID'],['message','Message'],['status','Process status'],['time','Received']]},
  outbox:{desc:'Monitor queued and delivered WhatsApp messages.',cols:[['recipient','Recipient'],['id','Message ID'],['message','Message'],['status','Send status'],['time','Updated']]}
  ,catalog:{desc:'Browse active motorcycle models and approved product images.',cols:[['brand','Brand'],['model','Model'],['variant','Variant'],['category','Category'],['fuel','Fuel'],['tier','Popularity'],['stock','Stock check']]}
  ,pricing:{desc:'Approved customer-facing loan rates. Cash price and internal notes are never displayed.',cols:[['brand','Brand'],['model','Model'],['variant','Variant'],['zone','Price zone'],['deposit','Deposit'],['year3','3 years'],['year4','4 years'],['year5','5 years'],['effective','Effective from']]}
  ,team:{desc:'Active sales advisors and their assigned branches.',cols:[['id','SA ID'],['name','Sales advisor'],['branch','Branch'],['region','Region'],['accepting','Accepting leads'],['lastAssigned','Last assigned']]}
 };
 const cfg=configs[view],rows=liveRecords[view];
 if(view==='catalog'){
  app.innerHTML=head(pageNames[view],cfg.desc,'Product operations')+`<article class="card table-card"><div class="toolbar"><input id="recordSearch" placeholder="Search brand or modelâ€¦"><span class="pill green">${rows.length} active models</span></div><div class="catalog-grid" id="catalogGrid"></div></article>`;
  const render=q=>{const filtered=rows.filter(r=>!q||Object.values(r).join(' ').toLowerCase().includes(q));document.getElementById('catalogGrid').innerHTML=filtered.map(r=>`<article class="motor-card"><div class="motor-image">${r.image?`<img src="${r.image}" alt="${r.brand} ${r.model}" loading="lazy" onerror="this.parentElement.innerHTML='<span>Image unavailable</span>'">`:'<span>Image pending approval</span>'}</div><div class="motor-body"><div class="eyebrow">${r.brand}</div><h3>${r.model}</h3><p>${r.variant||'Standard'} Â· ${r.category||'Motorcycle'}</p><div><span class="pill green">${r.tier||'ACTIVE'}</span><span class="pill">${r.stock||'CHECK_BRANCH'}</span></div></div></article>`).join('')||'<p>No matching models found.</p>'};
  render('');document.getElementById('recordSearch').oninput=e=>render(e.target.value.toLowerCase());return;
 }
 const statusOptions=[...new Set(rows.map(row=>row.status).filter(Boolean))].sort();
 const filterOptions=view==='pricing'?'<select id="recordFilter"><option value="">All price zones</option><option value="EAST_MALAYSIA">East Malaysia</option><option value="WEST_MALAYSIA">West Malaysia</option></select>':view==='team'?'<select id="recordFilter"><option value="">All regions</option><option value="SARAWAK">Sarawak</option><option value="WEST_MALAYSIA">West Malaysia</option></select>':statusOptions.length?`<select id="recordFilter"><option value="">All statuses</option>${statusOptions.map(status=>`<option value="${status}">${status.replaceAll('_',' ')}</option>`).join('')}</select>`:'';
 app.innerHTML=head(pageNames[view],cfg.desc,'Live operations')+`<article class="card table-card"><div class="toolbar"><input id="recordSearch" placeholder="Search recordsâ€¦">${filterOptions}<span class="pill green" id="resultCount">${rows.length} live records</span></div><table class="data-table"><thead><tr>${cfg.cols.map(c=>`<th>${c[1]}</th>`).join('')}${['applications','inbox'].includes(view)?'<th></th>':''}</tr></thead><tbody id="recordRows"></tbody></table></article>`;
 const display=(key,value)=>key==='accepting'?(String(value).toUpperCase()==='TRUE'?'Yes':'No'):['zone','region','status','stage'].includes(key)?String(value||'â€”').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()):value||'â€”';
 const render=()=>{const q=document.getElementById('recordSearch').value.toLowerCase(),filter=document.getElementById('recordFilter')?.value||'';const filtered=rows.filter(r=>(!q||Object.values(r).join(' ').toLowerCase().includes(q))&&(!filter||r.zone===filter||r.region===filter||r.status===filter));document.getElementById('recordRows').innerHTML=filtered.map(r=>`<tr>${cfg.cols.map(([key])=>`<td>${escapeHtml(display(key,r[key]))}</td>`).join('')}${view==='applications'?`<td><button class="row-action" data-edit-application="${escapeHtml(r.id)}">Open</button></td>`:view==='inbox'?`<td><button class="row-action" data-reply-inbox="${escapeHtml(r.id)}">Reply</button></td>`:''}</tr>`).join('')||`<tr><td colspan="${cfg.cols.length+1}">No records found.</td></tr>`;document.getElementById('resultCount').textContent=`${filtered.length} live records`};
 render(); document.getElementById('recordSearch').oninput=render;if(document.getElementById('recordFilter'))document.getElementById('recordFilter').onchange=render;
}
async function loadRecordsView(view){
 app.innerHTML=head(pageNames[view],'Loading live CRM recordsâ€¦')+'<article class="card empty-view"><div><h2>Loadingâ€¦</h2></div></article>';
 try{const cacheBust=view==='catalog'?`&_=${Date.now()}`:'';const response=await fetch(`/api/crm?resource=${view}${cacheBust}`,view==='catalog'?{cache:'no-store'}:undefined),payload=await response.json();if(!response.ok||!payload.live)throw new Error();liveRecords[view]=payload.records||[];if(document.querySelector('.nav-item.active')?.dataset.view===view)recordsView(view)}catch(error){toast('Unable to load live records. Please refresh and try again.')}
}
function settingsView(){app.innerHTML=head('Settings','Connection status and operating safeguards for JomKaki Motor CRM.','Administration')+`<div class="section-grid"><article class="card"><div class="card-head"><h2>Data connections</h2><span class="pill green">Operational</span></div><div class="list"><div class="list-row"><div class="list-icon">âœ“</div><div><strong>Google Sheets CRM</strong><span>Secure live read and controlled write access</span></div><span class="pill green">Connected</span></div><div class="list-row"><div class="list-icon">!</div><div><strong>WhatsApp Business Cloud</strong><span>Meta verification and Make connection still required</span></div><span class="pill">Pending</span></div></div></article><article class="card"><div class="card-head"><h2>Safety controls</h2></div><div class="list"><div class="list-row"><div class="list-icon">âœ“</div><div><strong>Cash price hidden</strong><span>Never returned by the CRM pricing API</span></div><span class="pill green">Enforced</span></div><div class="list-row"><div class="list-icon">âœ“</div><div><strong>Approved pricing only</strong><span>Draft and inactive rates are excluded</span></div><span class="pill green">Enforced</span></div><div class="list-row"><div class="list-icon">âœ“</div><div><strong>Controlled CRM writes</strong><span>Only approved operational fields can be changed</span></div><span class="pill green">Protected</span></div></div></article></div>`}
function placeholder(view){const title=pageNames[view];app.innerHTML=head(title,`The ${title.toLowerCase()} workspace is ready for the live Google Sheets connection.`)+`<article class="card empty-view"><div><div class="empty-icon">${view==='catalog'?'â—‡':'â–¦'}</div><h2>${title} module ready</h2><p>The interface foundation is complete. Live records, filters and actions will appear here after the secure Google Sheets data connection is enabled.</p><button class="primary" data-toast>Preview connection flow</button></div></article>`;document.querySelector('[data-toast]').onclick=()=>toast('Google Sheets connection will be added in Phase 2.')}
function setView(view){nav.forEach(n=>n.classList.toggle('active',n.dataset.view===view));view==='dashboard'?dashboard():view==='leads'?leadsView():view==='settings'?settingsView():['applications','inbox','outbox','catalog','pricing','team'].includes(view)?loadRecordsView(view):placeholder(view);document.getElementById('sidebar').classList.remove('open');window.scrollTo(0,0)}
function updateProfile(){const name=currentUser.name||currentUser.username||'CRM User',role=currentUser.role==='ADMIN'?'Administrator':pretty(currentUser.region)+' Manager';document.getElementById('profileName').textContent=name;document.getElementById('profileRole').textContent=role;document.getElementById('profileAvatar').textContent=name.split(' ').slice(0,2).map(part=>part[0]).join('').toUpperCase()||'JK'}
async function loadLiveCrm(){
 try{
  const [summaryResponse,leadsResponse,sessionResponse]=await Promise.all([fetch('/api/crm?resource=dashboard'),fetch('/api/crm?resource=leads'),fetch('/api/crm?resource=session')]);
  if(summaryResponse.status===401||leadsResponse.status===401||sessionResponse.status===401){appShell.hidden=true;loginGate.classList.remove('hidden');return false}
  if(!summaryResponse.ok||!leadsResponse.ok||!sessionResponse.ok){appShell.hidden=true;loginGate.classList.remove('hidden');return false}
  const summaryPayload=await summaryResponse.json(),leadsPayload=await leadsResponse.json(),sessionPayload=await sessionResponse.json();
  if(sessionPayload.user){currentUser=sessionPayload.user;updateProfile()}
  if(summaryPayload.live){crmSummary=summaryPayload.summary;isLive=true}
  if(leadsPayload.live&&Array.isArray(leadsPayload.records))leads=leadsPayload.records;
  appShell.hidden=false;
  loginGate.classList.add('hidden');
  const leadBadge=document.querySelector('[data-view="leads"] b'),applicationBadge=document.querySelector('[data-view="applications"] b'),inboxBadge=document.querySelector('[data-view="inbox"] i');
  if(leadBadge)leadBadge.textContent=crmSummary.leads;if(applicationBadge)applicationBadge.textContent=crmSummary.applications;if(inboxBadge)inboxBadge.textContent=crmSummary.unreadInbox;
  const notificationBadge=document.querySelector('.icon-button em');if(notificationBadge)notificationBadge.textContent=crmSummary.needsAttention;
  if(document.querySelector('.nav-item.active')?.dataset.view==='dashboard')dashboard();
  return true;
 }catch(error){appShell.hidden=true;loginGate.classList.remove('hidden');console.info('CRM login required');return false}
}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
nav.forEach(n=>n.addEventListener('click',()=>setView(n.dataset.view)));
document.getElementById('menuButton').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('newLeadButton').onclick=async()=>{const button=document.getElementById('newLeadButton');button.disabled=true;button.textContent='Refreshingâ€¦';await loadLiveCrm();const active=document.querySelector('.nav-item.active')?.dataset.view;if(['applications','inbox','outbox','catalog','pricing','team'].includes(active))await loadRecordsView(active);button.disabled=false;button.textContent='â†» Refresh data';toast('CRM data refreshed.')};
document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){setView('leads');setTimeout(()=>{document.getElementById('leadSearch').value=e.target.value;filterLeads()},0)}});
document.querySelector('.icon-button').onclick=()=>{setView('applications');toast(`${crmSummary.needsAttention} case${crmSummary.needsAttention===1?'':'s'} need attention.`)};
document.querySelector('.integration-card button').onclick=()=>{setView('settings');toast('WhatsApp Cloud connection is pending Meta verification.')};
document.getElementById('logoutButton').onclick=async()=>{await fetch('/api/logout');currentUser={name:'',role:'',region:''};leads=[];isLive=false;appShell.hidden=true;document.getElementById('loginUsername').value='';document.getElementById('loginPassword').value='';loginGate.classList.remove('hidden')};
loginForm.addEventListener('submit',async event=>{event.preventDefault();const button=loginForm.querySelector('button'),error=document.getElementById('loginError');button.disabled=true;button.textContent='Signing inâ€¦';error.textContent='';try{const response=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:document.getElementById('loginUsername').value,password:document.getElementById('loginPassword').value})});if(!response.ok)throw new Error('Incorrect username or password.');document.getElementById('loginPassword').value='';if(!await loadLiveCrm())throw new Error('Unable to load CRM data. Please try again.');dashboard()}catch(loginError){appShell.hidden=true;loginGate.classList.remove('hidden');error.textContent=loginError.message}finally{button.disabled=false;button.textContent='Sign in'}});
document.addEventListener('click',event=>{const add=event.target.closest('[data-add-lead]');if(add)return openNewLead();const editLead=event.target.closest('[data-edit-lead]');if(editLead){const lead=leads.find(item=>item.id===editLead.dataset.editLead);if(lead)return openLeadEditor(lead)}const editApplication=event.target.closest('[data-edit-application]');if(editApplication){const record=liveRecords.applications.find(item=>item.id===editApplication.dataset.editApplication);if(record)return openApplicationEditor(record)}const reply=event.target.closest('[data-reply-inbox]');if(reply){const record=liveRecords.inbox.find(item=>item.id===reply.dataset.replyInbox);if(record)return openMessageComposer({phone:record.customer})}});
document.addEventListener('click',event=>{if(!event.target.closest('[data-export]'))return;const rows=[...document.querySelectorAll('table tr')].map(row=>[...row.children].map(cell=>`"${cell.innerText.replaceAll('"','""')}"`).join(','));if(!rows.length)rows.push('Metric,Value',`Total leads,${crmSummary.leads}`,`Applications,${crmSummary.applications}`,`Needs attention,${crmSummary.needsAttention}`);const blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`jomkaki-crm-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href);toast('CSV export created.')});
dashboard();
loadLiveCrm();

